services:
  database:
    image: mongo:7.0.0
    container_name: mongo
    ports:
      - 27017:27017
  backend:
    build: ./demo
    image: khongtrunght/rule-backend
    container_name: demo
    ports:
      - 8080:80
    depends_on:
      - database

  frontend:
    build: ./demo-ui
    image: khongtrunght/rule-frontend
    container_name: demo_ui
    ports:
      - 4200:80
    depends_on:
      - backend
